# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.2'



---



## 배열 생성

### 리스트로 배열 만들기


In [3]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [4]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [5]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [8]:
np.full((3,3), 1.23) # 1.23으로 채워진 3x3 행렬

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성

In [9]:
np.eye(3) # 정사각형형태라 크기만

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성

In [11]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성

In [12]:
print(a1)
np.zeros_like(a1)   # a1과 같은 shape의 0행렬 생성

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [13]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [15]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [17]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

함수|설명
--|--
seed|난수 발생을 위한 시드(seed) 지정
permutation|순서를 임의로 바꾸거나 임의의 순열 반환
shuffle| 리스트나 배열의 순서를 뒤섞음
random|랜덤한 수의 배열 생성
rand|균등분포에서 표본 추출
randint|주어진 최소/최대 범위의 난수 추출
randn|표준편차가 1, 평균값 0인 정규분포의 표본 추출
binomial| 이항분포에서 표본 추출
normal|정규분포(가우시안)에서 표본 추출
beta|베타분포에서 표본 추출
chisquare|카이제곱분포에서 표본 추출
gamma|감마분포에서 표본 추출
uniform|균등(0,1)분포에서 표본 추출

* `random.random()`: 랜덤한 수의 배열 생성

In [18]:
np.random.random((3,3))

array([[0.11983367, 0.09717819, 0.77208033],
       [0.74352596, 0.90859936, 0.36306042],
       [0.20868351, 0.09133712, 0.08259066]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [19]:
np.random.randint(0, 10, (3,3))

array([[8, 8, 9],
       [7, 7, 4],
       [5, 9, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [20]:
np.random.normal(0, 1, (3,3))

array([[-0.16451197,  0.00839536, -1.78494483],
       [-0.36518057, -0.15585316, -0.17895811],
       [ 0.04947747,  0.65740703, -0.51706691]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.rand(3,3)

array([[0.25743239, 0.82861453, 0.62810324],
       [0.33717823, 0.32851428, 0.89251891],
       [0.98355264, 0.92610681, 0.01002349]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [22]:
np.random.randn(3,3)

array([[ 0.42814234, -1.04789343,  1.72188904],
       [-1.15815624,  0.78722814,  0.7213545 ],
       [-0.31095666, -0.47821701, -0.64565489]])

### 표준 데이터 타입

|데이터타입|설명|
|---|---|
|bool_|바이트로 저장된 불리언(Boolean)으로 True 또는 False 값을 가짐
|int_|기본 정수(Integer) 타입
|intc|C 언어에서 사용되는 `int`와 동일(일반적으로 `int32` 또는 `int64`)
|intp|인덱싱에 사용되는 정수 (C 언어에서 `ssize_t`와 동일; 일반적으로 `int32`또는 `int64`)
|int8|바이트(Byte)(-128~127)
|int16|정수(-32768~32767)
|int32|정수(-2147483648~2147483647)
|int64|정수(-9223372036854775808~9223372036854775807)
|uint8|부호 없는 정수(0~255)
|uint16|부호 없는 정수(0~65535)
|uint32|부호 없는 정수(0~4294967295)
|uint64|부호 없는 정수(0~18446744073709551615)
|float16|반정밀 부동 소수점(Half precision float):부호 비트, 5비트 지수, 10비트 가수
|float32|단정밀 부동 소수점(Single precision float):부호 비트, 8비트 지수, 23비트 가수
|float64|qo정밀 부동 소수점(Double precision float):부호 비트, 11비트 지수, 520비트 가수
|float_|`float64`를 줄여서 표현
|complex64|복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현
|complex128|복소수, 두개의 64비트 부동 소수점으로 표현
|complex_|`complex128`를 줄여서 표현

In [23]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성

|코드|의미|상대적 시간 범위|절대적 시간 범위|
|--|--|--|--|
|`Y`|연|
|`M`|월
|`W`|주
|`D`|일
`h`|시
`m`|분
`s`|초
`ms`|밀리초
`us`|마이크로초
`ns`|나노초
`ps`|피코초
`fs`|펨토초
`as`|아토초

In [26]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [27]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [29]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [30]:
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("size:", array.size)
  print("itemsize:", array.itemsize) # 각 아이템 하나당 가지는 byte
  print("nbytes:", array.nbytes) # size x itemsize
  print("strides:", array.strides)

In [31]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [32]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [33]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


### 인덱싱(Indexing)

In [34]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [35]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [36]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [37]:
print(a1)
print(a1[0:2])
print(a1[0,])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
4
[4]
[4 6 5]
[5 4 6 5 4]


In [38]:
print(a2)
print(a2[1])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [39]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [40]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True False]
 [ True False False]
 [False False  True]]
[1 2 4 9]


### 팬시 인덱싱(Fancy Indedxing)

In [41]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
                [2, 0]])
print(a1[ind])  # fancy indexing에 따라 shape가 변한다

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [42]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row,col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [43]:
print(a1)
b1 = np.insert(a1, 0, 10) # 위치 0에 10을 추가
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [44]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2) 
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [45]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [46]:
 print(a2)
 a2[0, 0] = 1
 a2[1, 1] = 2
 a2[2, 2] = 3
 a2[0] = 1
 print(a2)
 a2[1:, 2] = 9
 print(a2)
 row = np.array([0, 1])
 col = np.array([1, 2])
 a2[row, col] = 0
 print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [47]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1) 

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [48]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [49]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0    # 원본 배열까지 값이 바뀌게 됨
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [50]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [51]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [52]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [53]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [54]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [55]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [56]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [57]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5,2))
print(n2)

[[1 7 4 1 6]
 [8 8 9 7 3]]
[[1 7]
 [4 1]
 [6 8]
 [8 9]
 [7 3]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [58]:
n2.resize((5,5))
print(n2)

[[1 7 4 1 6]
 [8 8 9 7 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [59]:
n2.resize((3,3))
print(n2)

[[1 7 4]
 [1 6 8]
 [8 9 7]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [60]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [61]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [62]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [63]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [64]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [65]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [66]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [68]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [69]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [70]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [71]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [72]:
a1 = np.arange(0, 10)
print(a1)
b1 , c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [73]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [74]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [75]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [76]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3,1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

|연산자|범용함수|설명|
|--|--|--|
|``+``|``np.add``|덧셈|
|``-``|``np.subtract``|뺄셈|
|``-``|``np.negative``|단항 음수|
|``*``|``np.multiply``|곱셈|
|``/``|``np.divide``|나눗셈|
|``//``|``np.floor_divide``|나눗셈 내림|
|``**``|``np.power``|지수 연산|
|``%``|``np.mod``|나머지 연산|

In [77]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [78]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[ 7  6  9  5  9  7  9 13 14]
[-5 -2 -3  3  1  5  5  3  4]
[ 6  8 18  4 20  6 14 40 45]
[0.16666667 0.5        0.5        4.         1.25       6.
 3.5        1.6        1.8       ]
[0 0 0 4 1 6 3 1 1]
[    1    16   729     4   625     6    49 32768 59049]
[1 2 3 0 1 0 1 3 4]


In [79]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 2 9]
 [1 5 5]
 [7 4 6]]
[[10  4 12]
 [ 5 10 11]
 [14 12 15]]
[[-8  0 -6]
 [ 3  0  1]
 [ 0  4  3]]
[[ 9  4 27]
 [ 4 25 30]
 [49 32 54]]
[[0.11111111 1.         0.33333333]
 [4.         1.         1.2       ]
 [1.         2.         1.5       ]]
[[0 1 0]
 [4 1 1]
 [1 2 1]]
[[     1      4  19683]
 [     4   3125   7776]
 [823543   4096 531441]]
[[1 0 3]
 [0 0 1]
 [0 0 3]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [80]:
a1 = np.random.randint(-10,10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 7 -9  0  4  2]
[7 9 0 4 2]
[7 9 0 4 2]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [81]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 7 -9  0  4  2]
[49 81  0 16  4]
[2.64575131        nan 0.         2.         1.41421356]


<ipython-input-81-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수 (Exponential and Log Function)

In [82]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[7 5 9 2 2]
[1.09663316e+03 1.48413159e+02 8.10308393e+03 7.38905610e+00
 7.38905610e+00]
[128.  32. 512.   4.   4.]
[49 25 81  4  4]


In [83]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 5 9 2 2]
[1.94591015 1.60943791 2.19722458 0.69314718 0.69314718]
[2.80735492 2.32192809 3.169925   1.         1.        ]
[0.84509804 0.69897    0.95424251 0.30103    0.30103   ]


#### 삼각 함수(Trigonometrical Function)

|함수|설명|
|--|--|
np.sin(array)|요소 별 사인
np.cos(array)|요소 별 코사인
np.tan(array)|요소 별 탄젠트
np.arcsin(array)|요소 별 아크 사인
np.arccos(array)|요소 별 아크 코사인
np.arctan(array)|요소 별 아크 탄젠트
np.arctan2(array1, array2)|요소 별 아크 탄젠트
np.sinh(array)|요소 별 하이퍼볼릭 사인
np.cosh(array)|요소 별 하이퍼볼릭 코사인
np.tanh(array)|요소 별 하이퍼볼릭 탄젠트
np.arcsinh(array)|요소 별 하이퍼볼릭 아크 사인
np.arccosh(array)|요소 별 하이퍼볼릭 아크 코사인
np.arctanh(array)|요소 별 하이퍼볼릭 아크 탄젠트
np.deg2rad(array)|요소별 각도에서 라디안 변환
np.rad2deg(array)|요소별 라디안에서 각도 변환
np.hypot(array1, array2)|요소별 유클리드 거리 계산

In [84]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [85]:
 x = [-1, 0, 1]
 print(x)
 print(np.arcsin(x))
 print(np.arccos(x))
 print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

|함수|NaN 안전 모드|설명|
|--|--|--|
np.sum|np.nansum|요소의 합 계산
np.cumsum|np.nancumsum|요소의 누적 합
np.diff|N/A|요소의 차분
np.prod|np.nanprod|요소의 곱 계산
np.cumprod|np.nancumprod|요소의 누적 곱
np.dot|N/A|점 곱
np.matmul|N/A|행렬 곱
np.tensordot|N/A|텐서 곱
np.cross|N/A|벡터곱
np.inner|N/A|내적
np.outer|N/A|외적
np.mean|np.nanmean|요소의 평균 계산
np.std|np.nanstd|표준 편차 계산
np.var|np.nanvar|분산계산
np.min|np.nanmin|최소값
np.max|np.nanmax|최대값
np.argmin|np.nanargmin|최소값 인덱스
np.argmax|np.nanargmax|최대값 인덱스

#### sum(): 합 계산

In [86]:
a2 = np.random.randint(1, 10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
37 37
[13 16  8] [13 16  8]
[13 14 10] [13 14 10]


#### cumsum(): 누적합 계산

In [87]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[ 4  9 13 20 24 27 29 36 37]
[[ 4  5  4]
 [11  9  7]
 [13 16  8]]
[[ 4  9 13]
 [ 7 11 14]
 [ 2  9 10]]


#### diff(): 차분 계산

In [88]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[[ 1 -1]
 [-3 -1]
 [ 5 -6]]
[[ 3 -1 -1]
 [-5  3 -2]]
[[ 1 -1]
 [-3 -1]
 [ 5 -6]]


#### prod(): 곱 계산

In [89]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
94080
[ 56 140  12]
[80 84 14]


#### cumprod(): 누적곱 계산

In [90]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[    4    20    80   560  2240  6720 13440 94080 94080]
[[  4   5   4]
 [ 28  20  12]
 [ 56 140  12]]
[[ 4 20 80]
 [ 7 28 84]
 [ 2 14 14]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [91]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [14 14 14]
 [10 10 10]]
[[13 13 13]
 [14 14 14]
 [10 10 10]]


#### tensordot(): 텐서곱 계산

In [92]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
37
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]
[[13 13 13]
 [14 14 14]
 [10 10 10]]


#### cross(): 벡터곱

In [93]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [94]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [14 14 14]
 [10 10 10]]
[[4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]]


#### mean(): 평균 계산

In [95]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
4.111111111111111
[4.33333333 5.33333333 2.66666667]
[4.33333333 4.66666667 3.33333333]


#### std(): 표준 편차 계산

In [96]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
1.9116278371205837
[2.05480467 1.24721913 1.24721913]
[0.47140452 1.69967317 2.62466929]


#### var(): 분산 계산

In [97]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
3.654320987654321
[4.22222222 1.55555556 1.55555556]
[0.22222222 2.88888889 6.88888889]


#### min(): 최소값

In [98]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
1
[2 4 1]
[4 3 1]


#### max(): 최대값

In [99]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
7
[7 7 4]
[5 7 7]


#### argmin(): 최소값 인덱스

In [100]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
8
[2 1 2]
[0 2 2]


#### argmax(): 최대값 인덱스

In [101]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
3
[1 2 0]
[1 0 1]


#### median(): 중앙값

In [102]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[4 5 4]
 [7 4 3]
 [2 7 1]]
4.0
[4. 5. 3.]
[4. 4. 2.]


#### percentile(): 백분위 수



In [103]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40 ,60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [104]:
a2 = np.array([[False, False, False],
              [False, True, True],
              [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [105]:
a2 = np.array([[False, False, True],
              [True, True, True],
              [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [106]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [107]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
[False False False]
[False False  True]


|비교 범용 함수|설명|
|--|--|
|``np.isclose``|배열 두개가 (z*1e+02)% 내외로 가까우면 True, 아니면 False|
|``np.isinf``|배열이 inf이면 True, 아니면 False|
|``np.isfinite``|배열이 inf, nan이면 False, 아니면 True|
|``np.isnan``|배열이 nan이면 True, 아니면 False|

In [108]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(np.isclose(a1, b1))

[1 2 3 4 5]
[ True  True  True False False]


In [109]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)

|연산자|비교 범용 함수|
|--|--|
|``&``|np.bitwise_and|
|``\|``|np.bitwise_or|
|``^``|np.bitwise_xor|
|``~``|np.bitwise_not|

In [110]:
a2 = np.arange(1, 10).reshape(3 ,3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [111]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[7 1 4 4 1 4 9 2 1 1]
[1 1 1 1 2 4 4 4 7 9]
[7 1 4 4 1 4 9 2 1 1]
[1 4 8 9 7 2 3 5 0 6]
[7 1 4 4 1 4 9 2 1 1]
None
[1 1 1 1 2 4 4 4 7 9]


In [112]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[5 8 3]
 [4 9 7]
 [2 5 5]]
[[2 5 3]
 [4 8 5]
 [5 9 7]]
[[3 5 8]
 [4 7 9]
 [2 5 5]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [113]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1,3))

[8 1 8 9 7 4 1 6 2 1]
[1 1 1 2 6 4 7 9 8 8]


In [114]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[8 1 9 9 9]
 [3 9 1 1 9]
 [9 8 9 7 1]
 [5 3 1 1 9]
 [1 7 8 1 2]]
[[1 8 9 9 9]
 [1 1 3 9 9]
 [7 1 8 9 9]
 [1 1 3 5 9]
 [1 1 2 7 8]]
[[5 3 1 1 1]
 [1 1 8 1 2]
 [3 7 1 1 9]
 [8 8 9 7 9]
 [9 9 9 9 9]]
[[1 8 9 9 9]
 [1 1 3 9 9]
 [7 1 8 9 9]
 [1 1 3 5 9]
 [1 1 2 7 8]]


## 배열 입출력

|함수|설명|파일종류|
|--|--|--|
|``np.save()``|Numpy 배열 객체 1개를 파일에 저장|바이너리|
|``np.savez()``|Numpy 배열 객체 여러개를 파일에 저장|바이너리|
|``np.load()``|Numpy 배ㅑ열 저장 파일로부터 객체 로딩|파이너리
|``np.loadtxt()``|텍트스 파일로부터 배열로딩|텍스트
|``np.savetxt()``|텍스트 파일에 Numpy 배열 객체 저장|텍스트|

In [115]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)

[[7 2 7 9 3]
 [4 4 7 7 5]
 [5 7 3 1 8]
 [3 7 5 7 7]
 [6 8 3 3 1]]


In [116]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[1 2 8 8 5]
 [6 3 1 3 7]
 [4 5 9 2 5]
 [9 5 2 2 2]
 [2 5 1 3 1]]


In [117]:
npy = np.load("a.npy")
print(npy)

[[7 2 7 9 3]
 [4 4 7 7 5]
 [5 7 3 1 8]
 [3 7 5 7 7]
 [6 8 3 3 1]]


In [118]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[7 2 7 9 3]
 [4 4 7 7 5]
 [5 7 3 1 8]
 [3 7 5 7 7]
 [6 8 3 3 1]]
[[1 2 8 8 5]
 [6 3 1 3 7]
 [4 5 9 2 5]
 [9 5 2 2 2]
 [2 5 1 3 1]]


In [119]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[7 2 7 9 3]
 [4 4 7 7 5]
 [5 7 3 1 8]
 [3 7 5 7 7]
 [6 8 3 3 1]]


In [120]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[7. 2. 7. 9. 3.]
 [4. 4. 7. 7. 5.]
 [5. 7. 3. 1. 8.]
 [3. 7. 5. 7. 7.]
 [6. 8. 3. 3. 1.]]


In [121]:
print((b2))
np.savetxt("b.csv", b2, delimiter=',',fmt='%.2e', header='c1, c2, c3, c4, c5')

[[1 2 8 8 5]
 [6 3 1 3 7]
 [4 5 9 2 5]
 [9 5 2 2 2]
 [2 5 1 3 1]]


In [122]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[1. 2. 8. 8. 5.]
 [6. 3. 1. 3. 7.]
 [4. 5. 9. 2. 5.]
 [9. 5. 2. 2. 2.]
 [2. 5. 1. 3. 1.]]




---

